openapi: 3.0.3
info:
  contact:
    email: Simon.Schulz01@telekom.de
    name: Simon Schulz
  description: This is the REST api specification for the blockchain-adapter
  title: Blockchain-Adapter
  version: 0.0.8
servers:
- url: /
tags:
- description: Access to smartcontract data
  name: contract
- description: Access to configuration
  name: config
- description: Access to status information
  name: status
- description: Access to discovery information
  name: discovery
- description: Access to webhooks for event subscription
  name: webhook
paths:
  /discovery/msps:
    get:
      description: Show a list of all MSPs
      operationId: getDiscoveryMSPs
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: A list of all discovered MSPs
        "500":
          content: {}
          description: Internal Error
      tags:
      - discovery
      x-eov-operation-handler: controllers/DiscoveryController
  /discovery/msps/{mspid}:
    get:
      description: Show details for a specific MSP
      operationId: getDiscoveryMSP
      parameters:
      - description: Name of a MSP
        explode: false
        in: path
        name: mspid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: Details about the requested MSP
        "500":
          content: {}
          description: Internal Error
      tags:
      - discovery
      x-eov-operation-handler: controllers/DiscoveryController
  /status:
    get:
      description: Show version information of the API
      operationId: getApiStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: The status of the service
        "500":
          content: {}
          description: Internal Error
      tags:
      - status
      x-eov-operation-handler: controllers/StatusController
  /private-documents:
    get:
      description: show all private documents that are in the transient storage
      operationId: fetchPrivateDocumentIDs
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful operation, returns stored documentIDs _FIXME_ use
            proper content type _FIXME_
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
    post:
      description: Upload a private document, shared between our own organization
        and a partner MSP
      operationId: uploadPrivateDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrivateDocument'
        description: A document that should be uploaded
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateDocumentAdded'
          description: Successful operation, returns the documentID and the txID of
            the stored document
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/ContractController
  /private-documents/{id}:
    delete:
      description: Delete a private document from the database, identified by its
        id
      operationId: deletePrivateDocument
      parameters:
      - description: The document ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content: {}
          description: Successful deletion
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
    get:
      description: Fetch a private document from the database, identified by its id
      operationId: fetchPrivateDocument
      parameters:
      - description: The document ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateDocumentResponse'
          description: Successful operation, returns document
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /webhooks/subscribe:
    post:
      callbacks:
        onData:
          '{$request.query.callbackUrl}':
            post:
              operationId: onData_Post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SubscriptionPayload'
                description: subscription payload
              responses:
                "202":
                  description: the app should return this when the data was received
                    successfully
                "204":
                  description: the app should return this when it is no longer interested
                    in further updates
              x-callback-request: true
      description: subscribes a client to receive the specified event
      operationId: webhooksSubscribePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
        description: A document that should be uploaded
      responses:
        "201":
          content:
            text/plain:
              schema:
                description: The unique identifier of the associated subscription
                  (subscriptionID)
                example: 2531329f-fb09-4ef7-887e-84e648214436
                type: string
          description: Subscription successfully created
        "500":
          content: {}
          description: Internal Server Error
      tags:
      - webhook
      x-eov-operation-handler: controllers/WebhookController
  /webhooks/{subscriptionID}:
    delete:
      description: unsubscribes a client from the specified event
      operationId: webhooksSubscriptionIDDELETE
      parameters:
      - description: The unique identifier of the subscription you want to unsubscribe
          from
        explode: false
        in: path
        name: subscriptionID
        required: true
        schema:
          example: 2531329f-fb09-4ef7-887e-84e648214436
          type: string
        style: simple
      responses:
        "200":
          content: {}
          description: Subscription successfully deleted
        "404":
          content: {}
          description: Subscription not found
        "500":
          content: {}
          description: Internal Server Error
      tags:
      - webhook
      x-eov-operation-handler: controllers/WebhookController
  /webhooks:
    get:
      description: show all subscriptions
      operationId: webhooksGET
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: List of Subscriptions
        "500":
          content: {}
          description: Internal Server Error
      tags:
      - webhook
      x-eov-operation-handler: controllers/WebhookController
  /signatures/{id}:
    put:
      description: store a signature for the document identified by id on the ledger
      operationId: uploadSignature
      parameters:
      - description: The document ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentSignature'
        description: a document signature that should be uploaded
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Successful operation, returns transaction hash
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/ContractController
  /signatures/{id}/{msp}:
    get:
      description: Fetch all signatures for a given msp and a given document id from
        the ledger
      operationId: fetchSignatures
      parameters:
      - description: The document ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: A MSP name
        explode: false
        in: path
        name: msp
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
          description: Successful operation, returns json of signatures
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /signatures/{id}/{msp}/verify:
    put:
      description: Fetch all signatures for a given msp and a given document id from
        the ledger and verify the content against a given document
      operationId: verifySignatures
      parameters:
      - description: The document ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: A MSP name
        explode: false
        in: path
        name: msp
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                description: BUGBUG openapi dies not like string bodies?! Use json
                  array for now
                example: '["data..."]'
                type: string
              type: array
        description: A document to be used to verify the signatures
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
          description: Successful operation, returns json of verified signatures
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /config/offchain-db:
    put:
      description: Update the configuration of the offchain-db
      operationId: setOffchainDBConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OffchainDBConfig'
        description: A configuration for the offchain-db
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
          description: Successful operation, returns transaction hash
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - config
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/ConfigController
  /config/certificates/root:
    get:
      description: Read back the configuration of the offchain-db
      operationId: getOffchainDBConfig
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OffchainDBConfig'
          description: The current configuration for the offchain-db
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - config
      x-eov-operation-handler: controllers/ConfigController
    put:
      description: Upload a root certificate
      operationId: setCertificateRoot
      requestBody:
        content:
          application/json:
            schema:
              items:
                description: BUGBUG openapi dies not like string bodies?! Use json
                  array for now
                example: '["-----BEGIN CERTIFICATE-----..."]'
                type: string
              type: array
        description: Set the signature root certificate.
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
          description: Successful operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
          description: Internal Error
      tags:
      - config
      x-eov-operation-handler: controllers/ConfigController
components:
  schemas:
    PrivateDocument:
      example:
        data: data
        toMSP: toMSP
      properties:
        toMSP:
          description: The partner MSP that is also involved
          type: string
        data:
          description: A base64 encoded document
          type: string
      required:
      - data
      - toMSP
      title: PrivateDocument
      type: object
    PrivateDocumentAdded:
      example:
        txID: txID
        documentID: documentID
      properties:
        documentID:
          description: The documentID of the document that was added
          type: string
        txID:
          description: The hyperledger TX ID of the successfull add
          type: string
      required:
      - documentID
      - txID
      title: PrivateDocumentAdded
      type: object
    ErrorCode:
      properties:
        code:
          description: The error code. See chaincode/hybrid/errorcodes/errors.go for
            a list
          enum:
          - ERROR_NON_LOCAL_ACCESS_DENIED
          - ERROR_OFFCHAIN_DB_CONFIG
          - ERROR_INTERNAL
          - ERROR_DOCUMENT_ID_EXISTS
          - ERROR_DOCUMENT_ID_INVALID
          - ERROR_DOCUMENT_ID_UNKNOWN
          - ERROR_TARGET_MSP_INVALID
          - ERROR_CERT_INVALID
          - ERROR_SIGNATURE_INVALID
          - ERROR_BAD_JSON
          - ERROR_HASH_MISMATCH
          type: string
        message:
          description: The description of the error
          type: string
      required:
      - code
      - message
      title: ErrorCode
      type: object
    PrivateDocumentResponse:
      allOf:
      - $ref: '#/components/schemas/PrivateDocument'
      example:
        fromMSP: fromMSP
        dataHash: dataHash
        id: id
        timestamp: timestamp
      properties:
        fromMSP:
          description: The MSP that creates this document (optional on request)
          type: string
        dataHash:
          description: The hash over the document
          type: string
        timestamp:
          description: The timestamp when the document was stored in the local database.
          type: string
        id:
          description: The document ID
          type: string
      required:
      - dataHash
      - fromMSP
      - id
      - timestamp
      title: PrivateDocumentResponse
      type: object
    SubscriptionRequest:
      example:
        eventName: STORE:SIGNATURE
        callbackUrl: https://myapp.local
      properties:
        eventName:
          description: The Event name
          enum:
          - STORE:SIGNATURE
          - STORE:DOCUMENTHASH
          type: string
        callbackUrl:
          description: The location where data will be sent
          example: https://myapp.local
          format: uri
          type: string
      required:
      - callbackUrl
      - eventName
      title: Subscription
      type: object
    SubscriptionPayload:
      example:
        data: data
        eventName: eventName
        msp: msp
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        timestamp:
          description: The timestamp when the tx was created on the ledger (RFC3339)
          format: date-time
          type: string
        eventName:
          description: The Event name
          type: string
        msp:
          description: The MSP that triggered the event
          type: string
        data:
          description: The data payload
          type: string
      required:
      - data
      - eventName
      - msp
      - timestamp
      title: SubscriptionPayload
      type: object
    DocumentSignature:
      example:
        signature: signature
        certificate: |-
          -----BEGIN CERTIFICATE-----
          MIICYjCCAemgAwIBA...
        algorithm: secp384r1
      properties:
        algorithm:
          description: The algorithm used to sign
          example: secp384r1
          type: string
        certificate:
          description: The certificate of the signer in pem format
          example: |-
            -----BEGIN CERTIFICATE-----
            MIICYjCCAemgAwIBA...
          type: string
        signature:
          description: The digital signature over the document
          type: string
      required:
      - algorithm
      - certificate
      - signature
      title: DocumentSignature
      type: object
    OffchainDBConfig:
      example:
        URI: http://user:password@localhost:5984/
      properties:
        URI:
          description: URL of the offchain db (couchdb)
          example: http://user:password@localhost:5984/
          format: uri
          type: string
      required:
      - URI
      title: OffchainDBConfig
      type: object
