title: OffchainDBAdapterConfig
type: object
properties:
  restURI:
    type: string
    description: URL of the offchain db adapter
    format: uri
    example: 'http://offchain-db-adapter:3333/documents'
required:
  - restURI