# SPDX-FileCopyrightText: 2021 GSMA and all contributors.
#
# SPDX-License-Identifier: Apache-2.0
#
title: OffchainDBConfig
type: object
properties:
  URI:
    type: string
    description: URL of the offchain db (couchdb)
    format: uri
    example: 'http://user:password@localhost:5984/'
required:
  - URI