openapi: 3.0.1
info:
  title: Blockchain-Adapter
  description: This is the REST api specification for the blockchain-adapter
  version: 0.0.5
  contact:
    name: Simon Schulz
    email: Simon.Schulz01@telekom.de
tags:
  - name: contract
    description: Access to smartcontract data
  - name: config
    description: Access to configuration
  - name: status
    description: Access to status information
  - name: discovery
    description: Access to discovery information
  - name: webhook
    description: Access to webhooks for event subscription
paths:
  /discovery/msps:
    get: 
      description: Show a list of all MSPs
      tags:
        - discovery
      operationId: getDiscoveryMSPs
      responses:
        '200':  
          description: A list of all discovered MSPs
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        '500':
          description: Internal Error
          content: {}
  /discovery/msps/{mspid}:
    get:
      description: Show details for a specific MSP
      tags:
        - discovery
      operationId: getDiscoveryMSP
      parameters:
        - in: path
          name: mspid
          required: true
          schema:
            type: string
          description: Name of a MSP
      responses:
        '200':  
          description: Details about the requested MSP
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        '500':
          description: Internal Error
          content: {}
  /status:
    get:
      description: Show version information of the API
      tags:
        - status
      operationId: getApiStatus
      responses:
        '200':  
          description: The status of the service
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        '500':
          description: Internal Error
          content: {}
  /private-documents:
    post:
      description: Upload a private document, shared between our own organization and a partner MSP
      tags:
        - contract
      operationId: uploadPrivateDocument
      requestBody:
        description: A document that should be uploaded
        content:
          application/json:
            schema:
              $ref: models/PrivateDocument.yaml
        required: true
      responses:
        '200':  
          description: Successful operation, returns ID of stored document
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        '400':
          description: Bad Request
          content: {}
        '500':
          description: Internal Error
          content: {}
      x-codegen-request-body-name: body
    get:
      description: show last n private documents
      tags:
        - contract
      operationId: fetchPrivateDocuments
      responses:
        '200':  
          description: Successful operation, returns stored documents
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: models/PrivateDocument.yaml
        '500':
          description: Internal Error
          content: {}
  /private-documents/{id}:
    get:
      description: Fetch a private document from the database, identified by its id
      tags:
        - contract
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The document ID
      operationId: fetchPrivateDocument
      responses:
        '200':
          description: Successful operation, returns document
          content:
            application/json:
              schema:
                $ref: models/PrivateDocumentResponse.yaml
        '500':
          description: Internal Error
          content: {}
  /webhooks/subscribe:
    post:
      description: subscribes a client to receive the specified event
      tags:
        - webhook
      requestBody:
        description: A document that should be uploaded
        content:
          application/json:
            schema:
              $ref: models/SubscriptionRequest.yaml
      responses:
        '201':
          description: Subscription successfully created
          content:
            text/plain:
              schema:
                type: string
                description: The unique identifier of the associated subscription (subscriptionID)
                example: 2531329f-fb09-4ef7-887e-84e648214436
        '500':
          description: Internal Server Error
          content: {}
      callbacks:
        # the name `onData` is a convenience locator
        onData:
          # when data is sent, it will be sent to the `callbackUrl` provided
          '{$request.query.callbackUrl}':
            post:
              requestBody:
                description: subscription payload
                content:
                  application/json:
                    schema:
                      $ref: models/SubscriptionPayload.yaml
              responses:
                '202':
                  description: the app should return this when the data was received successfully
                '204':
                  description: the app should return this when it is no longer interested in further updates
  /webhooks/{subscriptionID}:
    delete:
      description: unsubscribes a client from the specified event
      tags:
        - webhook
      parameters:
        - in: path
          name: subscriptionID          
          required: true
          description: The unique identifier of the subscription you want to unsubscribe from
          schema:
            type: string
            example: 2531329f-fb09-4ef7-887e-84e648214436
      responses:
        '200':
          description: Subscription successfully deleted
          content: {}
        '404':
          description: Subscription not found
          content: {}
        '500':
          description: Internal Server Error
          content: {}

  /signatures/{id}:
    put:
      description: 'store a signature for the document identified by id on the ledger'
      tags:
        - contract
      operationId: uploadSignature
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The document ID
      responses:
        '200':
          description: Successful operation, returns transaction hash
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content: {}
      requestBody:
        description: a document signature that should be uploaded
        content:
          application/json:
            schema:
              $ref: models/DocumentSignature.yaml
        required: true
      x-codegen-request-body-name: body
  /signatures/{id}/{msp}:
    get:
      description: Fetch all signatures for a given msp and a given document id from the ledger
      tags:
        - contract
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The document ID
        - in: path
          name: msp
          required: true
          schema:
            type: string
          description: A MSP name
      operationId: fetchSignatures
      responses:
        '200':
          description: Successful operation, returns json of signatures
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        '500':
          description: Internal Server Error
          content: {}
  /config/offchain-db-adapter:
    put:
      description: Update the configuration of the offchain-db-adapter
      tags:
        - config
      operationId: setOffchainDBAdapterConfig
      requestBody:
        description: A configuration for the offchain-db-adapter
        content:
          application/json:
            schema:
              $ref: models/OffchainDBAdapterConfig.yaml
        required: true
      responses:
        '200':
          description: Successful operation, returns transaction hash
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        '500':
          description: Internal Error
          content: {}
      x-codegen-request-body-name: body
    get:
      description: Read back the configuration of the offchain-db-adapter
      tags:
        - config
      operationId: getOffchainDBAdapterConfig
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: models/OffchainDBAdapterConfig.yaml
          description: The current configuration for the offchain-db-adapter
        '500':
          description: Internal Error
          content: {}
