# SPDX-FileCopyrightText: 2021 the BWRP-blockchain-adapter contributors.
#
# SPDX-License-Identifier: Apache-2.0
name: build_docker

on:
  # build on new v* tag push
  push:
    tags:
      - v*
  # allow manual trigger
  workflow_dispatch:

jobs:
   build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: checkout source
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: build and publish
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        build-context: ./server
        dockerfile: ./server/Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: blockchain-adapter
        image-tag: ${{ steps.get_version.outputs.VERSION }}
